baseURL = "https://www.inbeat.co/"
DefaultContentLanguage = "en"
title = ""
theme = "inbeat"
description = ""

# Pointing to this file
config = "config.toml"
contentdir = "content"
disableKinds = ["RSS", "tags"]
# Create an array of files you don't want hugo to build
ignoreFiles = [".+/assets/scss/.+"]
# Enable Logging
log = false
preserveTaxonomyNames = true
pygmentsUseClasses = true
relativeURLs = true
languageCode = "en-us"
metaDataFormat = "yaml"
defaultContentLanguageInSubdir = false

#CUSTOM PARAMS
[params]
  ## This is used when the BaseURL does not need to modified (eg, in share links)
  siteaddress = "https://www.inbeat.co/"
  siteaddressno = "https://www.inbeat.co"
  ## Google Tag Manager tracking ID
  gtmid = "GTM-W2MQ972"

# MARKDOWN
## Configuration for BlackFriday markdown parser: https://github.com/russross/blackfriday
[blackfriday]
  plainIDAnchors = true
  hrefTargetBlank = true
  angledQuotes = false
  latexDashes = true

[markup.goldmark.renderer]
  unsafe= true

[permalinks]
  singles = "/:slug/"

# [Languages.fr]
# [Languages.fr.Taxonomies]
# category = "categories"
# createur = "createurs"
