# theme.toml template for a Hugo theme
# See https://github.com/spf13/hugoThemes#themetoml for an example

name = "InBeat"
license = ""
description = ""
homepage = ""
tags = ["", ""]
features = ["", ""]
min_version = 0.24

[author]
  name = "Akia Marketing Inc"
  homepage = "akiamarketing.ca"

